server:
  port: ${SERVER_PORT:8080}
spring:
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [health, prometheus]
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}


logging:
  level:
    org.pircbotx: WARN
    pub.edholm.irc2rss: ${LOG_LEVEL:DEBUG}
    org.springframework.http.client.support: DEBUG
irc2rss:
  torrentleech:
    enabled: ${TL_ENABLED:true}
    host: ${TL_IRC_SERVER:irc.torrentleech.org}
    port: ${TL_IRC_PORT:7011}
    nick: ${TL_NICK}
    nickserv-pwd: ${TL_NICKSERV_PWD}
    rsskey: ${TL_RSS_KEY}
    autojoin-channel: ${TL_AUTOJOIN_CHANNEL:#tlannounces}
    ssl: ${TL_SSL:false}
  category:
    max-size: ${CATEGORY_MAX_SIZE:100}
    filter:
      - TV_EPISODES_HD
      - MOVIES_4K
  sonarr:
    - app-name: sonarr
      enabled: ${SONARR_NOTIFY_ENABLED:true}
      url: ${SONARR_URL:https://luna.lan.elee.cloud/sonarr}
      api-key: ${SONARR_API_KEY:}
      categories:
        - TV_EPISODES_HD
    - app-name: radarr
      enabled: ${RADARR_NOTIFY_ENABLED:true}
      url: ${RADARR_URL:https://luna.lan.elee.cloud/radarr}
      api-key: ${RADARR_API_KEY:}
      categories:
        - MOVIES_4K

