server:
  port: ${SERVER_PORT:8080}
spring:
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://localhost:27017/irc2rss
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [health, prometheus]
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}


logging:
  level:
    org.pircbotx: WARN
    pub.edholm.irc2rss: ${LOG_LEVEL:DEBUG}

irc2rss:
  torrentleech:
    enabled: ${TL_ENABLED:true}
    host: ${TL_IRC_SERVER:irc.torrentleech.org}
    port: ${TL_IRC_PORT:7011}
    nick: ${TL_NICK}
    nickserv-pwd: ${TL_NICKSERV_PWD}
    rsskey: ${TL_RSS_KEY}
    autojoin-channel: ${TL_AUTOJOIN_CHANNEL:#tlannounces}
    ssl: ${TL_SSL:false}
  category:
    filter:
      - TV_EPISODES_HD
  hook:
    enabled: ${HOOK_ENABLED:true}
    url: ${HOOK_URL:http://localhost:1234/sb.forcesearch}
    expected-return-code: ${HOOK_EXPECTED_RETURN_CODE:200}
    only-hook-on-filtered: ${HOOK_ONLY_ON_FILTERED:true}
