package pub.edholm.irc2rss.domain

enum class Category {
  ANIME,
  APPLICATIONS_MAC,
  APPLICATIONS_PC,
  BOOKS_COMICS,
  GAMES_PC,
  GAMES_PS4,
  MOVIES_4K,
  MOVIES_BLURAY,
  MOVIES_BLURAY_RIP,
  MOVIES_DOCUMENTARIES,
  MOVIES_DVDRIP,
  MOVIES_DVDSCREENER,
  MOVIES_FOREIGN,
  MOVIES_WEBRIP,
  MUSIC_VIDEOS,
  TV_BOXSETS,
  TV_EPISODES,
  TV_EPISODES_HD,
  TV_FOREIGN,
  UNKNOWN
}